version: '3.8'

services:
  postgres:
    image: postgres:13.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    networks:
      - app_net

  rails_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - METRICS_VICTORIAMETRICS_ENDPOINT=vmagent
      - METRICS_VICTORIAMETRICS_PORT=8125
    volumes:
      - .:/app
    networks:
      - vm_net
      - app_net

  rails_migrations:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    volumes:
      - .:/app
    networks:
      - app_net
    command: >
      /bin/sh -c "
      bundle exec rails db:create db:migrate"

  vmagent:
    image: victoriametrics/vmagent:latest
    depends_on:
      - "victoriametrics"
    ports:
      - 8429:8429
      - 8125:8125/udp
    volumes:
      - vmagent_data:/vmagentdata
      - ./scrape_config.yml:/etc/scrape_config.yml
      - ./aggregation_config.yaml:/etc/config/aggregation_config.yaml
    command:
      - "--promscrape.config=/etc/scrape_config.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
      - "--remoteWrite.streamAggr.config=/etc/config/aggregation_config.yaml"
      - "-statsdListenAddr=:8125"
    networks:
      - vm_net
    restart: always

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.101.0
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 4242:4242
    volumes:
      - vm_data:/storage
    command:
      - "--storageDataPath=/storage"
      - "--opentsdbListenAddr=:4242"
      - "-logNewSeries"
    networks:
      - vm_net
    restart: always

  grafana:
    image: grafana/grafana:9.2.7
    depends_on:
      - "victoriametrics"
    ports:
      - 3001:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning/
      - ./dashboards/victoriametrics.json:/var/lib/grafana/dashboards/vm.json
      - ./dashboards/vmagent.json:/var/lib/grafana/dashboards/vmagent.json
      - ./dashboards/rails-routes.json:/var/lib/grafana/dashboards/rails-routes.json
    networks:
      - vm_net
    restart: always

volumes:
  postgres:
  vmagent_data: {}
  vm_data: {}
  grafana_data: {}

networks:
  vm_net:
  app_net:
