{
 "title": "API",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "step",
    "query": "30s,1m,5m,15m,30m,1h,3h,6h,12h,1d"
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(rails.request.time:count_samples{}, controller)"
    }
   },
   {
    "name": "action",
    "query": {
     "query": "label_values(rails.request.time:count_samples{controller=~\"^$controller$\"}, action)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\", status!=\"\"}))",
     "legendFormat": "Success requests"
    },
    {
     "expr": "sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", exception!=\"\"}))",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "Total requests by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(label_transform(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\", status!=\"\"}), \"status\", \"(.)..\", \"$1**\")) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(rails.request.time:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n/\nsum(sum_over_time(rails.request.time:count_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Average requests per second",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"})) / $step",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "running_sum(sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\", exception!=\"\"})))\n/\nrunning_sum(sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"})))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "5xx status rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "running_sum(sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\", status=~\"^5.*.*$\"})))\n/\nrunning_sum(sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\", status!=\"\"})))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Total requests by controller and action(top 20)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk_max(20, sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"})) by (controller, action))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Actions with the most errors(top 20)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk_max(20, sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\", exception!=\"\"})) by (controller, action))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "5xx statuses producers(top 20)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk_max(20, sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\", status=~\"^5.*.*$\"})) by (controller, action))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Top 20 exceptions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk_max(20, sum(sum_over_time(rails.request.total:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\", exception!=\"\"})) by (exception))",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "Total time spent(top 40)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk_max(40, sum(sum_over_time(rails.request.time:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"})) by (controller, action))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Total time spent(top 40). Pie chart",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk_max(40, sum(sum_over_time(rails.request.time:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"})) by (controller, action))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Total time spent distribution. Pie chart",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(rails.request.time:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n-\nsum(sum_over_time(rails.request.time.db:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n-\nsum(sum_over_time(rails.request.time.view:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))",
     "legendFormat": "Other"
    },
    {
     "expr": "sum(sum_over_time(rails.request.time.db:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(sum_over_time(rails.request.time.view:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))",
     "legendFormat": "Render"
    }
   ]
  },
  {
   "title": "Average time spent distribution. Pie chart",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n    sum(sum_over_time(rails.request.time:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n    /\n    sum(sum_over_time(rails.request.time:count_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n)\n-\n(\n    sum(sum_over_time(rails.request.time.db:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n    /\n    sum(sum_over_time(rails.request.time.db:count_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n)\n-\n(\n    sum(sum_over_time(rails.request.time.view:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n    /\n    sum(sum_over_time(rails.request.time.view:count_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n)",
     "legendFormat": "Other"
    },
    {
     "expr": "sum(sum_over_time(rails.request.time.db:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n/\nsum(sum_over_time(rails.request.time.db:count_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(sum_over_time(rails.request.time.view:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n/\nsum(sum_over_time(rails.request.time.view:count_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))",
     "legendFormat": "Render"
    }
   ]
  },
  {
   "title": "Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "prometheus_buckets(sum(increase(rails.request.time:histogram_bucket{controller=~\"^$controller$\", action=~\"^$action$\"}[$step])) by (vmrange))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"quantile\", 0.5, 0.95, 0.99, sum(rate(rails.request.time:histogram_bucket{controller=~\"^$controller$\", action=~\"^$action$\"}[$step])) by (vmrange))",
     "legendFormat": "{{quantile}} percentile"
    },
    {
     "expr": "sum(sum_over_time(rails.request.time:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))\n/\nsum(sum_over_time(rails.request.time:count_samples{controller=~\"^$controller$\", action=~\"^$action$\"}))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Slowest routes(median)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk_max(20, histogram_quantile(0.5, sum(rate(rails.request.time:histogram_bucket{controller=~\"^$controller$\", action=~\"^$action$\"}[$step])) by (vmrange, controller, action)))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Average time spent in DB per request(top 20)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk_max(20, \nsum(sum_over_time(rails.request.time.db:sum_samples{controller=~\"^$controller$\", action=~\"^$action$\"})) by (controller, action)\n/\nsum(sum_over_time(rails.request.time.db:count_samples{controller=~\"^$controller$\", action=~\"^$action$\"})) by (controller, action)\n)",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  }
 ]
}