{
 "title": "Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "step", "query": "1m,5m,10m,30m,1h,3h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Average metrics delivery delay",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(timestamp(metrics_delivery_delay_check:last) - metrics_delivery_delay_check:last)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total data sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(datadog.dogstatsd.client.bytes_sent:sum_samples))"
    }
   ]
  },
  {
   "title": "Delivery delay quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantiles(\"quantile\", 0.5, 0.95, 0.99, timestamp(metrics_delivery_delay_check:last) - metrics_delivery_delay_check:last)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Number of metrics sent(quantiles)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"quantile\", 0.5, 0.99, 0.95, sum(rate(datadog.dogstatsd.client.metrics:histogram_bucket[$step])) by (vmrange))",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Bytes sent quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"quantile\", 0.5, 0.95, 0.99, sum(rate(datadog.dogstatsd.client.bytes_sent:histogram_bucket[$step])) by (vmrange))",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Bytes sent heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "prometheus_buckets(sum(increase(datadog.dogstatsd.client.bytes_sent:histogram_bucket[$step])) by (vmrange))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Metrics sent heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "prometheus_buckets(sum(increase(datadog.dogstatsd.client.metrics:histogram_bucket[$step])) by (vmrange))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Top 15 most frequently sent metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk_max(15, sum(sum_over_time({__name__=~\".*:count_samples\"}) keep_metric_names) by (__name__))",
     "legendFormat": "{{k8s_proctype}}"
    }
   ]
  },
  {
   "title": "Bytes dropped",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(datadog.dogstatsd.client.bytes_dropped:sum_samples) > 0) by (k8s_proctype)",
     "legendFormat": "{{k8s_proctype}}"
    }
   ]
  },
  {
   "title": "Packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(datadog.dogstatsd.client.packets_dropped:sum_samples) > 0) by (k8s_proctype)",
     "legendFormat": "{{k8s_proctype}}"
    }
   ]
  },
  {
   "title": "Bytes dropped queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(datadog.dogstatsd.client.bytes_dropped_queue:sum_samples) > 0) by (k8s_proctype)",
     "legendFormat": "{{k8s_proctype}}"
    }
   ]
  }
 ]
}